### PR TITLE
Create harbour-marker-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
First (Swedish) translation if wanted.

### CODE REVIEW

**Comment by eson57** [comment]
I found two missing translation strings during test session.

screenshot-18-07-15-07-50-59
screenshot-18-07-15-07-53-27

**Comment by steffen-foerster** [comment]
Thanks for the Swedish translation. I have added the missing translation strings. Can you test it again?

**Comment by eson57** [comment]
Sorry, cant make those two strings translate.

**Comment by steffen-foerster** [comment]
It's working. Thanks.

**Comment by steffen-foerster** [comment]
Version 0.5.5 with your translation is in Jolla Harbour.

**Comment by eson57** [comment]
Thanks a lot.

**Comment by eson57** [comment]
Is there a long delay at Jolla Harbour? It still says version 0.5.4.

**Comment by steffen-foerster** [comment]
Status in Jolla Harbour is still QA.

**Pull request merged**
